"use client";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import Dashboard from "~/components/Dashboard";
import Navbar from "~/components/Navbar";

import { api } from "~/utils/api";

export default function Home() {
  const router = useRouter();
  const { status } = useSession();

  if (status === "unauthenticated") {
    router.push("/signin");
  }
  return (
    <>
      <Head>
        <title>Blackbox</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className=" flex min-h-screen flex-col items-center justify-center">
        <Dashboard />
      </main>
    </>
  );
}
