"use client";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import Dashboard from "~/components/Dashboard";
import Newsletter from "~/components/DesignSystem/Newsletter";
import Navbar from "~/components/Navbar";

export default function Home() {
  const router = useRouter();
  const { status } = useSession();

  if (status === "authenticated") {
    return (
      <>
        <Head>
          <title>Blackbox</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />
        <main className="flex min-h-screen flex-col items-center justify-center">
          <Dashboard />
        </main>
      </>
    );
  } else if (status === "loading") {
    return (
      <div className="font-2xl flex min-h-screen items-center justify-center px-4 py-12 text-2xl font-bold sm:px-6 lg:px-8">
        Loading...
      </div>
    );
  } else {
    // router.push("signin");
    return (
      <div className="font-2xl flex min-h-screen items-center justify-center px-4 py-12 text-2xl font-bold sm:px-6 lg:px-8">
        <Newsletter />
      </div>
    );
  }
}
